[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "coralscapes"
version = "0.1.0"
description = "The Coralscapes Dataset: Semantic Scene Understanding in Coral Reefs"

[tool.setuptools]
packages = { find = { where = ["."] } }