# """
# # Resources: 
# # Oquab, M., Darcet, T., Moutakanni, T., Vo, H., Szafraniec, M., Khalidov, V., ... & Bojanowski, P. (2023). 
# # Dinov2: Learning robust visual features without supervision. arXiv preprint arXiv:2304.07193.
# # https://github.com/facebookresearch/dinov2/issues/153
# # https://github.com/NielsRogge/Transformers-Tutorials/tree/master/DINOv2
# # https://huggingface.co/blog/Isayoften/monocular-depth-estimation-guide
# # """

run_name: "dpt-dinov2-base_lora_run"

augmentation:
  train:
    Resize:
      width: 1036
      height: 518
    HorizontalFlip:
      p: 0.5
    RandomCrop:
      width: 518
      height: 518
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  val:
    Resize:
      width: 1036
      height: 518
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  test:
    Resize:
      width: 1036
      height: 518
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      
model:
  name: "dpt-dinov2-base"

training:
  epochs: 1000
  optimizer:
    type: torch.optim.AdamW
    lr: 0.0005
    weight_decay: 0.01
  scheduler:
    type: torch.optim.lr_scheduler.PolynomialLR
    power: 1
    total_iters: 1000
  eval: 
    transform_target: False

lora:
  r: 128
  lora_alpha: 32
  modules_to_save: ["head"]
